Autograd package provides automatic differentiation

In [1]:
import torch

In [2]:
x = torch.tensor([[1, 2], [3, 4]], requires_grad=True, dtype=torch.float32)
print(x)

tensor([[1., 2.],
        [3., 4.]], requires_grad=True)


In [3]:
y = x-2
print(y)

tensor([[-1.,  0.],
        [ 1.,  2.]], grad_fn=<SubBackward0>)


In [5]:
y.grad_fn

In [10]:
y.grad_fn.next_functions[0][0], y.grad_fn.next_functions[0][0].variable

(<AccumulateGrad at 0x1ec091ab080>,
 tensor([[1., 2.],
         [3., 4.]], requires_grad=True))

In [11]:
z = y * y * 3
a = z.mean()

print(z)
print(a)

tensor([[ 3.,  0.],
        [ 3., 12.]], grad_fn=<MulBackward0>)
tensor(4.5000, grad_fn=<MeanBackward0>)


In [14]:
from torchviz import make_dot

In [15]:
make_dot(a)

ExecutableNotFound: failed to execute ['dot', '-Tsvg'], make sure the Graphviz executables are on your systems' PATH

#### Gradients

In [16]:
a.backward()

In [17]:
print(x.grad)

tensor([[-1.5000,  0.0000],
        [ 1.5000,  3.0000]])


In [18]:
x = torch.randn(3, requires_grad=True)

y = x*2
i = 0
while y.data.norm() < 1000:
    y = y*2
    i += 1
print(y)

tensor([1164.2745,  857.6931,  -73.9244], grad_fn=<MulBackward0>)


In [19]:
# if we don't run backward on a scalar we need to specify the grad_output
gradients = torch.FloatTensor([0.1, 1.0, 0.0001])
y.backward(gradients)

print(x.grad)

tensor([5.1200e+01, 5.1200e+02, 5.1200e-02])


In [20]:
print(i)

8


### Inference

In [21]:
n = 5

In [22]:
x = torch.arange(1., n+1, requires_grad=True)
w = torch.ones(n, requires_grad=True)
z = w @ x

z.backward()

print(x.grad, w.grad, sep='\n')

tensor([1., 1., 1., 1., 1.])
tensor([1., 2., 3., 4., 5.])


In [23]:
x = torch.arange(1., n+1)
w = torch.ones(n, requires_grad=True)
z = w @ x

z.backward()

print(x.grad, w.grad, sep='\n')

None
tensor([1., 2., 3., 4., 5.])


In [24]:
x = torch.arange(1.0, n+1)
w = torch.ones(n, requires_grad=True)

with torch.no_grad():
    z = w @ x
    
try:
    z.backward()
except RuntimeError as e:
    print(e)

element 0 of tensors does not require grad and does not have a grad_fn
